name: Greetings

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: 'Greet new contributors'
        uses: garg3133/welcome-new-contributors@v1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
           'Hi @contributor_name, thank you for your interest in Mitiq! If this is a bug report, please provide screenshots and/or **minimum viable code to reproduce your issue**,  so we can do our best to help get it fixed. If you have any questions in the meantime, you can also ask us on the [Unitary Fund Discord](https://discord.unitary.fund).'
          pr-message: |
          'Hi @contributor_name, thank you for submitting a PR! We will respond as soon as possible, and if you have any questions in the meantime, you can ask us on the [Unitary Fund Discord](https://discord.unitary.fund).'